### ISSUE TITLE
HeaderToolScrollBar 滚没了。。。

### ISSUE THREAD

**Issue by aThinkerbomb** [Super-lying/LySegmentMenu#1]
index+1 >= self.maxShowNum/2+1 && index+1 <= self.titleCount - (self.maxShowNum/2+0)  
这句是 changeSelectItemWithIndex: 方法中的，我一直想不明白你这个条件判断是什么意思，以至于我写的东西出现了bug，罪魁祸首就是进入了这个条件，走了scrollRectToVisible:animated: 这个方法，导致HeaderToolScrollBar 直接滚动到该区域，上面的Bar 不见了，很是痛苦，找了一下午终于确定是这个自己滚动方法 的问题。我查阅了任何资料都没人发现这个bug，不过我发现了。你可以这样写个demo:   window.rootVC = TabBarVC，TabBarVC -> Navigation -> tablviewController.  你照这个结构做完，然后把你的LysegmentMenu add到上面，记住，需要传三个view和三个title，当你点击第二的时候，奇迹就会发生。因为不知道你 if 里条件的逻辑，所以我没办法修改，暂时只能把他注释掉了。希望您能给出解答。QQ：466270590.谢谢！！！🙏

**Comment by Luy7788** [comment]
这个之前回复后忘记在这边写了：需要在viewcontroller设置self.automaticallyAdjustsScrollViewInsets = NO；
